### Assignment No- 2
### Name : Divya Tukaram Sale
### Roll No : 19121009
### Subject : Machine Learning
### Class : BE(Comp)

## Import Required Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn import metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

## Load the Dataset

In [2]:
data=pd.read_csv('emails.csv')

## Data Preprocessing

In [3]:
#First five records 
data.head()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   
3   Email 4    0   5   22    0    5   1   51    2   10  ...         0    0   
4   Email 5    7   6   17    1    5   2   57    0    9  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  
3       0    0               0         0         0   0    0           0  
4       0    0               0         0         0   1    0           0  

[5 rows x 3002 columns]

In [4]:
#Last five records
data.tail()

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  \
5167  Email 5168    2   2    2    3    0   0   32    0    0  ...         0   
5168  Email 5169   35  27   11    2    6   5  151    4    3  ...         0   
5169  Email 5170    0   0    1    1    0   0   11    0    0  ...         0   
5170  Email 5171    2   7    1    0    2   1   28    2    0  ...         0   
5171  Email 5172   22  24    5    1    6   5  148    8    2  ...         0   

      jay  valued  lay  infrastructure  military  allowing  ff  dry  \
5167    0       0    0               0         0         0   0    0   
5168    0       0    0               0         0         0   1    0   
5169    0       0    0               0         0         0   0    0   
5170    0       0    0               0         0         0   1    0   
5171    0       0    0               0         0         0   0    0   

      Prediction  
5167           0  
5168           0  
5169           1  
5170           1  
5171           0  

[5 rows x 3002 columns]

In [5]:
#Display Columns of Dataset
data.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [6]:
#Check missing values
data.isna()

Email No.    the     to    ect    and    for     of      a    you  \
0         False  False  False  False  False  False  False  False  False   
1         False  False  False  False  False  False  False  False  False   
2         False  False  False  False  False  False  False  False  False   
3         False  False  False  False  False  False  False  False  False   
4         False  False  False  False  False  False  False  False  False   
...         ...    ...    ...    ...    ...    ...    ...    ...    ...   
5167      False  False  False  False  False  False  False  False  False   
5168      False  False  False  False  False  False  False  False  False   
5169      False  False  False  False  False  False  False  False  False   
5170      False  False  False  False  False  False  False  False  False   
5171      False  False  False  False  False  False  False  False  False   

        hou  ...  connevey    jay  valued    lay  infrastructure  military  \
0     False  ...     False  False   False  False           False     False   
1     False  ...     False  False   False  False           False     False   
2     False  ...     False  False   False  False           False     False   
3     False  ...     False  False   False  False           False     False   
4     False  ...     False  False   False  False           False     False   
...     ...  ...       ...    ...     ...    ...             ...       ...   
5167  False  ...     False  False   False  False           False     False   
5168  False  ...     False  False   False  False           False     False   
5169  False  ...     False  False   False  False           False     False   
5170  False  ...     False  False   False  False           False     False   
5171  False  ...     False  False   False  False           False     False   

      allowing     ff    dry  Prediction  
0        False  False  False       False  
1        False  False  False       False  
2        False  False  False       False  
3        False  False  False       False  
4        False  False  False       False  
...        ...    ...    ...         ...  
5167     False  False  False       False  
5168     False  False  False       False  
5169     False  False  False       False  
5170     False  False  False       False  
5171     False  False  False       False  

[5172 rows x 3002 columns]

In [7]:
#Check Missing Values
data.isna().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [8]:
#Total Number of missing values in dataset
data.isna().sum().sum()

0

In [9]:
#Size od Dataset
data.size

15526344

In [10]:
#Shape of dataset
data.shape

(5172, 3002)

#### Divide Dataset into input(X) and Output(y)

In [11]:
X = data.iloc[:, 1:-1].values
y = data.iloc[:, -1].values

In [12]:
X.shape

(5172, 3000)

In [13]:
y.shape

(5172,)

#### Split the dataset into train and test

In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [15]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(4137, 3000)
(1035, 3000)
(4137,)
(1035,)


## 1.Support Vector Machine

#### Build the SVM Model

In [16]:
SVM_MOdel = svm.SVC(kernel='linear')
SVM_MOdel.fit(X_train,y_train)

SVC(kernel='linear')

In [17]:
Pred = SVM_MOdel.predict(X_test)

#### Performance of SVM Model

In [18]:
print("SVM Model accuracy:",metrics.accuracy_score(Pred,y_test))

SVM Model accuracy: 0.9565217391304348


In [19]:
print("Model1 precision:",metrics.precision_score(Pred,y_test))

Model1 precision: 0.921311475409836


In [20]:
print("Model1 recall:",metrics.recall_score(Pred,y_test))

Model1 recall: 0.9304635761589404


In [21]:
results = confusion_matrix(Pred,y_test)
print(results)

[[709  24]
 [ 21 281]]


# Accuracy of Support Vector Machine MOdel is 93.04

# 

## 2.K-Nearest Neighbors

#### Build the Model

In [22]:
KNN_Model=KNeighborsClassifier(n_neighbors=5)

#### Fit the Model

In [23]:
KNN_Model.fit(X_train,y_train)

KNeighborsClassifier()

In [24]:
Prediction=KNN_Model.predict(X_test)

In [25]:
y_test

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [26]:
Prediction

array([1, 1, 0, ..., 0, 0, 0], dtype=int64)

#### Performance of KNN Model

In [27]:
print(confusion_matrix(y_test,Prediction))

[[648  82]
 [ 45 260]]


In [28]:
print(classification_report(Prediction,y_test))

              precision    recall  f1-score   support

           0       0.89      0.94      0.91       693
           1       0.85      0.76      0.80       342

    accuracy                           0.88      1035
   macro avg       0.87      0.85      0.86      1035
weighted avg       0.88      0.88      0.88      1035



In [29]:
print("KNN Model accuracy:",metrics.accuracy_score(Prediction,y_test))

KNN Model accuracy: 0.8772946859903382


# Accuracy of KNN Model is 87.72